### ISSUE TITLE
웹 UI구상도

### ISSUE THREAD

**Issue by SeongMunHeo** [Who-IM/LeaveOutApp#13]
웹 UI 구상도 올려주세요

**Comment by ckdtjr3689** [comment]
# 첫화면
![default](https://cloud.githubusercontent.com/assets/26506143/24646790/15ce6e12-1958-11e7-93dc-89becda06ab6.png)

---

# 첫화면 + 메뉴 화면
![default](https://cloud.githubusercontent.com/assets/26506143/24646811/27a336f4-1958-11e7-81c7-c446b50bb3bd.png)

---

# 두번째 화면
![default](https://cloud.githubusercontent.com/assets/26506143/24646823/30774eaa-1958-11e7-9626-74cca824b750.png)

---
# 세번째 화면
![default](https://cloud.githubusercontent.com/assets/26506143/24646830/336c82ec-1958-11e7-8d78-941aacea8446.png)
