### ISSUE TITLE
앱 UI구상도

### ISSUE THREAD

**Issue by SeongMunHeo** [Who-IM/LeaveOutApp#9]
어플리케이션의 UI 구상도

**Comment by ckdtjr3689** [comment]
# 로그인 화면 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563471/b40bc3de-2dd7-11e7-9664-e6ce3219e8cb.png)

---

# 회원가입 화면 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563473/c6506162-2dd7-11e7-8f93-d267eefbc5c0.png)

---

**Comment by ckdtjr3689** [comment]
# 메인화면 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563474/dc076b54-2dd7-11e7-8558-c72ac907e09a.png)

---

# 울타리글 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563486/feb8fa0a-2dd7-11e7-9733-75e996ddd5da.png)

---

# 체크기능 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563488/0301a4c2-2dd8-11e7-98f7-5fa258f3b25e.png)

---

# 메인화면 + 프로필 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563489/0796de6c-2dd8-11e7-9743-26569e3bed81.png)

---
# 친구 목록 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563537/bbf663aa-2dd8-11e7-9bfe-32b315c20fdf.png)

**Comment by ckdtjr3689** [comment]
# 울타리글 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/24646470/0b38784a-1957-11e7-869a-54dadf9ebe42.png)

---

# 체크기능 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/24646484/1b3003c6-1957-11e7-8bc2-096969443e21.png)

**Comment by ckdtjr3689** [comment]
# 글쓰기 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563499/33792666-2dd8-11e7-8b24-fa5c60110c8e.png)

---

# 글쓰기 + 체크 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563501/36ad7d82-2dd8-11e7-81a0-9303711e72da.png)

**Comment by ckdtjr3689** [comment]
# 검색기능 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/24646587/7ef60a72-1957-11e7-9e2c-0f4afbb47885.png)

**Comment by ckdtjr3689** [comment]
# 글보기 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563517/5b251e36-2dd8-11e7-81ca-1a5c15a6904a.png)

---

# 모아보기 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563519/5fe956d0-2dd8-11e7-83e6-29f5af1f977a.png)

**Comment by ckdtjr3689** [comment]
# 프로필 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/25563522/6f490e2c-2dd8-11e7-9d3a-fe59d190f926.png)
![2](https://cloud.githubusercontent.com/assets/26506143/25563524/70b2afd4-2dd8-11e7-9bb4-96923c0e319d.png)

**Comment by ckdtjr3689** [comment]
# 검색기능 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/24647491/13f093e2-195b-11e7-9a8e-542df7eeedbe.png)

---

# 환경설정 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/24646703/c8f63b9c-1957-11e7-86cf-1918fe5a44b2.png)

---

# 푸쉬알림 구상도
![default](https://cloud.githubusercontent.com/assets/26506143/24646715/d009d95c-1957-11e7-9320-5686f9cd7872.png)

**Comment by ckdtjr3689** [comment]
# 친구 목록
![default](https://cloud.githubusercontent.com/assets/26506143/25563533/93bc5282-2dd8-11e7-9ce0-47d51cede091.png)
